# Generated by Django 4.2 on 2023-05-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_closeingtime_gym_closingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='type',
            field=models.CharField(choices=[('Unisex', 'Unisex'), ('Male', 'Male'), ('Female', 'Female')], default='Unisex', max_length=20),
        ),
    ]
