# Generated by Django 4.2 on 2023-05-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_gym_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='charge',
            field=models.IntegerField(default='1000'),
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(default='99990000', max_length=15),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('experience', models.IntegerField()),
                ('field', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=15)),
                ('certificate', models.ImageField(default='', upload_to='GymImg')),
                ('charge', models.IntegerField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=122)),
                ('end', models.CharField(max_length=122)),
                ('intake', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=100)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=122)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
