# Generated by Django 4.2 on 2023-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_trainer_certificate_remove_trainer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='closingtime',
            field=models.TimeField(max_length=122),
        ),
        migrations.AlterField(
            model_name='gym',
            name='openingtime',
            field=models.TimeField(max_length=122),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end',
            field=models.TimeField(max_length=122),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start',
            field=models.TimeField(max_length=122),
        ),
    ]
