# Generated by Django 4.2 on 2023-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_gym_closingtime_alter_gym_openingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='trainer1',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='slot',
            name='trainer2',
            field=models.CharField(default='', max_length=122),
        ),
    ]
