# Generated by Django 4.2 on 2023-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_slot_trainer1_slot_trainer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='booked',
            field=models.IntegerField(default=0),
        ),
    ]
