# Generated by Django 4.2 on 2023-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='price',
            new_name='slotprice',
        ),
        migrations.AddField(
            model_name='slot',
            name='totalprice',
            field=models.IntegerField(default=100),
        ),
    ]
